[package]
name = "nft_migration_app_v1"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v4.0.0-devnet.2-patch.0", directory = "aztec" }
aztec_state_migration = { path = "../../../aztec-state-migration" }
