[workspace]
members = [
    "aztec-state-migration",
    "contracts/migration-archive-registry",
    "contracts/migration-key-registry",
    "test-contracts/example-app/v1",
    "test-contracts/example-app/v2",
    "test-contracts/nft-migration-app/v1",
    "test-contracts/nft-migration-app/v2",
    "test-contracts/token-migration-app/v1",
    "test-contracts/token-migration-app/v2",
    "test-contracts/minimal-benchmark",
    "tests",
]
exclude = ["tests"]
