[workspace]
members = [
    "aztec-state-migration",
    "contracts/migration-archive-registry",
    "contracts/migration-key-registry",
    "test-contracts/example-app",
    "test-contracts/nft-migration-app",
    "tests",
]
exclude = ["tests"]
