name: Setup Aztec CLI
description: Install Aztec CLI binaries for the given version

inputs:
  version:
    description: Aztec version to install
    required: true

runs:
  using: composite
  steps:
    - name: Install Aztec CLI
      shell: bash
      run: |
        INSTALL_URL="https://install.aztec.network/${{ inputs.version }}/"
        curl -sL $INSTALL_URL > tmp.sh
        VERSION=${{ inputs.version }} bash tmp.sh <<< "yes"
        rm tmp.sh
    - name: Update path
      shell: bash
      run: |
        echo "$HOME/.aztec/current/bin" >> $GITHUB_PATH
        echo "$HOME/.aztec/current/node_modules/.bin" >> $GITHUB_PATH
        echo "$HOME/.aztec/bin" >> $GITHUB_PATH
