/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import MigrationKeyRegistryContractArtifactJson from "../artifacts/migration_key_registry-MigrationKeyRegistry.json" with { type: "json" };
export const MigrationKeyRegistryContractArtifact = loadContractArtifact(
  MigrationKeyRegistryContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract MigrationKeyRegistry;
 */
export class MigrationKeyRegistryContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, MigrationKeyRegistryContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MigrationKeyRegistryContract {
    return Contract.at(
      address,
      MigrationKeyRegistryContract.artifact,
      wallet,
    ) as MigrationKeyRegistryContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<MigrationKeyRegistryContract>(
      PublicKeys.default(),
      wallet,
      MigrationKeyRegistryContractArtifact,
      (instance, wallet) =>
        MigrationKeyRegistryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet) {
    return new DeployMethod<MigrationKeyRegistryContract>(
      publicKeys,
      wallet,
      MigrationKeyRegistryContractArtifact,
      (instance, wallet) =>
        MigrationKeyRegistryContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<
    M extends keyof MigrationKeyRegistryContract["methods"],
  >(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MigrationKeyRegistryContract["methods"][M]>
  ) {
    return new DeployMethod<MigrationKeyRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MigrationKeyRegistryContractArtifact,
      (instance, wallet) =>
        MigrationKeyRegistryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MigrationKeyRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      MigrationKeyRegistryContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<"registered_keys"> {
    return {
      registered_keys: {
        slot: new Fr(1n),
      },
    } as ContractStorageLayout<"registered_keys">;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** constructor() */
    constructor: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get(owner: struct) */
    get: ((owner: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** register(mpk: struct) */
    register: ((mpk: {
      x: FieldLike;
      y: FieldLike;
      is_infinite: boolean;
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
